[package]
name = "Î¼cc"
version = "0.1.0"
authors = ["Artemis Tosini <me@artem.ist>", "Skye Jensen <skyeajensen@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2.0"

[target.'cfg(fuzzing)'.dependencies]
#afl = "*"
honggfuzz = "0.5"